article/urls.py
from django.urls import path, include
from article import views
from article.models import Article

app_name = 'article'
urlpatterns = [
    path('', views.ArticleList.as_view(), name='list'),
    path('<pk>', views.ArticleDetail.as_view(), name='detail'),
    path('about/', views.about_page, name='about-me'),
]

translation/urls.py

from django.urls import path, include
from translation import views

app_name = 'translation'
urlpatterns = [
    path('', views.TransListView.as_view(), name='list'),
]

website/urls.py
from article.views import Home
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

from. import settings

urlpatterns = [
    # Django
    path('admin/', admin.site.urls),

    # Third party
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('martor/', include('martor.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
   
    # Custom
    path('', Home.as_view(), name='home-page'),
    path('article', include('article.urls')),
    path('translations', include('translation.urls')),
    path('whisper', include('whisper.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

whisper/urls.py
from django.shortcuts import render

from django.urls import path, include
from whisper import views
from whisper.models import Whisper

app_name = 'whisper'
urlpatterns = [
    path('', views.WhisperList.as_view(), name='list'),
    path('/test/', views.test, name='test')
]

article/models.py
from django.db import models
# from tinymce.models import HTMLField
# from ckeditor.fields import RichTextField
# from ckeditor_uploader.fields import RichTextUploadingField
from django.contrib.auth.models import User

from ckeditor_uploader.fields import RichTextUploadingField
from martor.models import MartorField

class Article(models.Model):
    title = models.CharField(max_length=100)
    content = MartorField()
    c_time = models.DateTimeField(auto_now=True)
    views = models.PositiveIntegerField(default=0)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    def increase_views(self):
        self.views += 1
        self.save(update_fields=['views'])
        return ''

    class Meta:
        db_table = 'article'
        verbose_name = u'文章'

transforum/models.py
from django.db import models
from django.contrib.auth.models import User


#整个翻译论坛的内容采用二层的树形结构
class TransTreeNode(models.Model):
    parent_id = models.IntegerField(default=-1)  # -1为根节点，代表原文否则为译文
    title = models.CharField(max_length=200, default='')
    content = models.TextField(blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    likes = models.PositiveIntegerField(default=0)
    c_time = models.DateTimeField(auto_now=True)

    def increase_likes(self):
        self.likes += 1
        self.save(update_fields=['likes'])

    class Meta:
        db_table = 'transforum_object'
        verbose_name = u'翻译'

translation/models.py
from django.db import models
from django.contrib.auth.models import User

#整个翻译论坛的内容采用二层的树形结构
class Trans(models.Model):
    parent_id = models.IntegerField(default=-1)#-1为根节点，代表原文否则为译文
    title = models.CharField(max_length=200, default='')
    content = models.TextField(blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    likes = models.PositiveIntegerField(default=0)

    def increase_likes(self):
        self.likes += 1
        self.save(update_fields=['likes'])

    class Meta:
        db_table = 'transforum_object'
        verbose_name = u'翻译'

whisper/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.models import User
from martor.models import MartorField


class Whisper(models.Model):
    content = MartorField()
    c_time = models.DateTimeField(auto_now=True)

    author = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.content[:40]

    class Meta:
        db_table = 'whisper'
        verbose_name = u'碎碎念'

article/views.py
from django.core import serializers
from django.shortcuts import render
from django.http import Http404
from django.http import HttpResponse
from django.views.generic import ListView, DetailView, View

from .models import Article

from website.settings import BASE_DIR


class Home(ListView):
    model = Article
    template_name = 'article/home.html'
    context_object_name = 'articles'

    def get_queryset(self):
        return Article.objects.order_by('-views')[:3]

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        context['jumbotron'] = Article.objects.order_by(
            'c_time').last()  
        return context


class ArticleList(ListView):
    model = Article
    paginate_by = 10
    template_name = 'article/article_list.html'
    context_object_name = 'articles'

    def get_queryset(self):
        return Article.objects.order_by('-c_time')


class ArticleDetail(DetailView):
    model = Article
    template_name = 'article/article_detail.html'
    context_object_name = 'article'

    # def get_queryset(self):
    #     return Article.objects.get(pk=self.kwargs['pk'])

def about_page(request):
    return render(request, 'article/about.html')


# FaV template
# def single_article_detail(request, article_id):
#     try:
#         article = Article.objects.get(pk=article_id)
#     except Article.DoesNotExist:
#         raise Http404("Article does not exist")
#     print(article.title, article.cover, "ddd")
#     return render(request, 'article/single_article.html', {'article': article})

from django.http import JsonResponse
from django.http import HttpResponse
from article.models import Article
from django.core import serializers
import json
def article_list(request):
    print(request.method)
    #articles = Article.objects.all()
    #serializer = serializers.serialize(articles, many=True)
    serializer = serializers.serialize("json", Article.objects.all())
    # js = Article.objects.all().values()
    # print(js)
    # js = json.loads(serializer)
    # print(js)
 
    # return JsonResponse(js, safe=False)
    return HttpResponse(serializer, content_type='application/json')

transforum/views.py
from django.shortcuts import render
from .models import TransTreeNode
# Create your views here.


class TransTree():
    model = TransTreeNode
    
    template_name = 'transforum/trans_tree.html'
    context_object_name = 'articles'

    def get_queryset(self):
        return Article.objects.order_by('-c_time')


def trans_tree(request):
    ctx = {}
    trans_objs = TransTreeNode.objects.order_by('-likes')
    for obj in trans_objs:
        if obj.parent_id==-1 and obj
        if obj.id in ctx:
            ctx[obj.id].append()

    return render(request, 'article/about.html',template_name=ctx)

translation/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views.generic import ListView, DetailView, View
from .models import Trans

from website.settings import BASE_DIR


class TransListView(ListView):
    model = Trans
    paginate_by = 10
    template_name = 'translation/translation_list.html'
    context_object_name = 'translations'



whisper/views.py
from django.shortcuts import render
from django.http import Http404
from django.http import HttpResponse
from django.views.generic import ListView, DetailView, View

from .models import Whisper

from website.settings import BASE_DIR


class WhisperList(ListView):
    model = Whisper
    paginate_by = 10
    template_name = 'whisper/whisper_list.html'
    context_object_name = 'whispers'

    def get_queryset(self):
        return Whisper.objects.order_by('-c_time')


def test(request):
    obj = Whisper.objects.order_by('-c_time')
    print(len(obj))
    return render(request, 'whisper/whisper_test.html', context={'whispers':obj})

templates/article/about.html
{% extends '../base.html' %}
{% block about %}
    <h4>
        <pre><b >联系我:bigpopwzc@gmail.com </b>
        陕ICP备19010284号	  
        </pre>
    </h4>
{% endblock %}

templates/article/article_detail.html
{% extends "../base.html" %}
{% block article-detail %}
{% load martortags %}
<div style="padding:5%">
    <h1 style="text-align: center">{{ article.title }}<br><br></h1>
    <div style="display: none">{{ article.increase_views }}</div>

    <div id="container" style="width:800px;margin: auto;left: 0;right: 0;">
        <div style="text-align: left">
            {{ article.content|safe_markdown}}
        </div>
        <br><br>
        <div style="float:right;text-align:center;padding: 0px;">
            <pre >{{ article.author.username }}<br>{{ article.c_time }}</pre>
        </div>
    </div>
</div>
{% endblock %}

templates/article/article_list.html
{% extends "../base.html" %}

{% block article-list %}

<div class="list-group">
    {% for article in articles %}
    <div style="padding-left: 15%;padding-right: 15%;padding-bottom: 0%;">
        <a href="{% url 'article:detail' article.id %}" class="list-group-item" style="padding-bottom: 3%;">
            <div style="float:left">
                <h4 class="list-group-item-heading">{{ article.title }}</h4>
            </div>
            <div style="float: right;">
                <p style="font-size: xx-small; color:#c8c8c8; float: right; ">
                    <b style="color: #646464">
                        {{ article.views }} Reads  
                    </b>
                    &nbsp&nbsp{{ article.c_time}}
                    
                </p>

            </div>
            
        </a>
    </div>
    {% endfor %}
</div>
<div>
<p>
    {{articles.number}}
</p>
</div>


{% if is_paginated %}
    <nav style="padding-left: 11%;padding-right: 11%;">
        <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Previous</a>
            </li>
            {% endif %}
    
            {% if page_obj.number|add:'-4' > 1 %}
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.number|add:'-5' }}">&hellip;</a></li>
            {% endif %}
    
            {% for i in page_obj.paginator.page_range %}
            {% if page_obj.number == i %}
            <li class="page-item active" aria-current="page">
                <span class="page-link">
                    {{ i }}
                    <span class="sr-only">(current)</span>
                </span>
            </li>
            {% elif i > page_obj.number|add:'-5' and i < page_obj.number|add:'5' %}
            <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
            {% endif %}
            {% endfor %}
    
            {% if page_obj.paginator.num_pages > page_obj.number|add:'4' %}
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.number|add:'5' }}">&hellip;</a></li>
            {% endif %}
    
            {% if page_obj.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Next</a>
            </li>
            {% endif %}
        </ul>
    </nav>
{% endif %}
{% endblock %}

templates/article/book_review.html
{% extends "../base.html" %}

{% block article-list %}
    {% for article in article_list%}
        <h1> <a href = "TODO">{{article.title}}</a></h1>
    {% endfor %}
{% endblock %}

templates/article/home.html
{% extends "../base.html" %}
{% load static %}

{% block home %}
<div class="jumbotron" style="text-align:left;padding-left:15%;">
    <h1>{{ jumbotron.title }}</h1>
    <p>
        <a class="btn btn-primary btn-lg" href="{% url 'article:list' %}" role="button">Learn more</a>
    </p>
</div>

<div class="media-object-default" style="padding-left: 10%;padding-right: 10%;">
    {% for article in articles%}
    <div class="media" style="border:2px solid #c8c8c8;padding:2px;">
        <a href="{% url  'article:detail' 'article.id' %}">
            <div  style="color: #646464;padding-left: 1%;padding-bottom: 0%;">
                <h4 class="media-heading">{{ article.title }}</h4>
            </div>
        </a>
    </div>
    {% endfor %}
</div>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="utf-8">
        <meta name="baidu-site-verification" content="code-ahSHZQgT8E" />
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>BIGPOP</title>
        <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet" type="text/css">
    </head>

    <body style="padding-top: 70px">
        <div>
            <nav class="navbar navbar-default navbar-fixed-top">
                <div class="container-fluid">
                    <!-- Brand and toggle get grouped for better mobile display -->
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                            data-target="#topFixedNavbar1" aria-expanded="false"><span class="sr-only">Toggle
                                navigation</span><span class="icon-bar"></span><span class="icon-bar"></span><span
                                class="icon-bar"></span></button>
                        <a href="{% url "home-page" %}"><img src="{% static "/img/logo.png" %}" width="50"></a>
                    </div>
                    <!-- Collect the nav links, forms, and other content for toggling -->
                    <div class="collapse navbar-collapse" id="topFixedNavbar1">
                        <ul class="nav navbar-nav">
                            <li><a href="{% url "article:list" %}">文章<span class="sr-only">(current)</span></a></li>
                            <li><a href="{% url "translation:list" %}">翻译</a></li>
                            <li><a href="{% url "whisper:list" %}">碎碎念</a></li>
                        </ul>
                        <ul class="nav navbar-nav navbar-right">
                            <li><a href="{% url "article:about-me" %}"><span class="glyphicon glyphicon-envelope"
                                        aria-hidden="true"></span></a></li>

                            <ul class="dropdown-menu">
                                <li><a href="#">Action</a></li>
                                <li><a href="#">Another action</a></li>
                                <li><a href="#">Something else here</a></li>
                                <li role="separator" class="divider"></li>
                                <li><a href="#">Separated link</a></li>
                            </ul>
                            </li>
                        </ul>
                    </div>
                    <!-- /.navbar-collapse -->
                </div>
                <!-- /.container-fluid -->
            </nav>
        </div>

        {% block home %}
        {% endblock %}

        {% block article-list %}
        {% endblock %}

        {% block article-detail %}
        {% endblock %}

        {% block about %}
        {% endblock %}

        {% block translate-list %}
        {% endblock %}

        {% block book-review %}
        {% endblock %}

        {% block whisper-list %}
        {% endblock %}
        <script src="../static/js/jquery-1.11.3.min.js"></script>
        <script src="../static/js/bootstrap.js"></script>
    </body>

</html>

templates/translation/translation_list.html
{% extends '../base.html' %}
{% block  translate-list%}

{% for tran in translations %}
<div class="panel-group" id="accordion{{ tran.id }}" role="tablist" aria-multiselectable="true"
    xmlns="http://www.w3.org/1999/html">
    <div class="pane{{ tran.id }} panel-default">
        <a data-toggle="collapse" data-parent="#accordion{{ tran.id }}" href="#collapse{{ tran.id }}">
            <div class="panel-heading" role="tab">
                <h4 class="panel-title">
                    {{ tran.title }}
                </h4>

            </div>
        </a>
        <div id="collapse{{ tran.id }}" class="panel-collapse collapse">
            <div class="panel-body" font="it">
                <i>
                    <p style="padding: 1%">{{ tran.origin|linebreaks }}</p>
                    {% ifnotequal tran.translated1 '' %}
                    <pre>{{ tran.translated1|linebreaks }}<br>   <div style="float: right">{{ tran.source1 }}</div> </pre>
                    {% endifnotequal %}

                    {% ifnotequal tran.translated2 '' %}
                    <pre>{{ tran.translated2 }}<br>   <div style="float: right">{{ tran.source2 }}</div> </pre>
                    {% endifnotequal %}

                    {% ifnotequal tran.translated3 '' %}
                    <pre>{{ tran.translated3 }}<br>   <div style="float: right">{{ tran.source3 }}</div> </pre>
                    {% endifnotequal %}
                    {% ifnotequal tran.translated4 '' %}
                    <pre>{{ tran.translated4}}<br>   <div style="float: right">{{ tran.source4 }}</div> </pre>
                    {% endifnotequal %}
                    {% ifnotequal tran.translated5 '' %}
                    <pre>{{ tran.translated5}}<br>   <div style="float: right">{{ tran.source5 }}</div> </pre>
                    {% endifnotequal %}

                </i>
            </div>
        </div>
    </div>
</div>
{% endfor %}


{% if is_paginated %}
<nav>
    <ul class="pagination">
        {% if page_obj.has_previous %}
        <li>
            <a href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
            </a>
        </li>
        {% else %}
        <li>
            <a href="" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
            </a>
        </li>
        {% endif %}


        <li class="disabled"><a href="?page{{ page_obj.number }}">第{{ page_obj.number }}页</a></li>



        {% if page_obj.has_next %}
        <li><a href="?page={{ page_obj.next_page_number }}" aria-label="Next"><span
                    aria-hidden="true">&raquo;</span></a></li>
        {% else %}
        <li>
            <a href="" aria-label="Previous">
                <span aria-hidden="true">&raquo;</span>
            </a>
        </li>
        {% endif %}

    </ul>
</nav>
{% endif %}

{% endblock %}

templates/whisper/whisper_list.html
{% extends "../base.html" %}
{% block whisper-list %}
{% load martortags %}
<div class="list-group">
    <div style="padding-left: 15%;padding-right: 15%;">
        <hr>
    </div>
    {% for whisper in whispers %}
    <div style="padding-left: 15%;padding-right: 15%;padding-bottom: 0%;display: flex;">
        
        <div style="width:85%;word-wrap: break-word;word-break: normal;">  
            <p >{{ whisper.content |safe_markdown}}</p>
        </div>
        <div style="padding-left:2%;font-size: xx-small;">
            <p style="bottom: 0%;color:#c8c8c8;">
                {{ whisper.c_time}}
            </p>
        </div>
        
    </div>
    <div style="padding-left: 15%;padding-right: 15%;">
        <hr>
    </div>
    {% endfor %}
</div>
<div>
    <p>
        {{whispers.number}}
    </p>
</div>
<!-- 

{% if is_paginated %}
<nav style="padding-left: 11%;padding-right: 11%;">
    <ul class="pagination justify-content-center">
        {% if page_obj.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Previous</a>
        </li>
        {% endif %}

        {% if page_obj.number|add:'-4' > 1 %}
        <li class="page-item"><a class="page-link" href="?page={{ page_obj.number|add:'-5' }}">&hellip;</a></li>
        {% endif %}

        {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
        <li class="page-item active" aria-current="page">
            <span class="page-link">
                {{ i }}
                <span class="sr-only">(current)</span>
            </span>
        </li>
        {% elif i > page_obj.number|add:'-5' and i < page_obj.number|add:'5' %}
        <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
        {% endif %}
        {% endfor %}

        {% if page_obj.paginator.num_pages > page_obj.number|add:'4' %}
        <li class="page-item"><a class="page-link" href="?page={{ page_obj.number|add:'5' }}">&hellip;</a></li>
        {% endif %}

        {% if page_obj.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Next</a>
        </li>
        {% endif %}
    </ul>
</nav>
{% endif %} -->
{% endblock %}

templates/whisper/whisper_test.html
{% extends '../base.html' %}
{% block whisper-list %}

{% for whisper in whispers %}
<h2>
<p>x</p>
    {{ whisper.content }}
</h2>
{% endfor %}

{% endblock %}